name = "shareable-workspace"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "FILES"
bucket_name = "workspace-files"

[[d1_databases]]
binding = "workspaces_db"
database_name = "workspaces-db"
database_id = "1dd5b8e8-ec8f-4d3f-88a6-223239f53021"

[triggers]
crons = ["* * * * *"]

[vars]
PARTYKIT_HOST = "localhost:1999"
